### ISSUE TITLE
[1.1] Vertical Content Alignment in Containers, Columnset

### ISSUE THREAD

**Issue by raghunandhan09** [Imaginea/AdaptiveCards#30]
https://github.com/microsoft/adaptivecards/issues/134

<h1>Feature</h1>

 Vertically align content within a column (or within a fixed height container like Timeline) to Top, Center or Bottom. Without vertical alignment on the body and containers itself, you won't be able to achieve the desired results.

<h1>Design</h1>
 <p>Add a new <strong>verticalContentAlignment</strong> property to <code>Container</code>, <code>Column</code>, and <code>AdaptiveCard</code>:</p>
   <table>
   <thead>
   <tr>
   <th>Property name</th>
   <th>Type</th>
   <th>Description</th>
   </tr>
   </thead>
   <tbody>
   <tr>
   <td>verticalContentAlignment</td>
   <td>string. Allowed values are <strong>"top"</strong> (default), <strong>"center"</strong>, and <strong>"bottom"</strong>.</td>
   <td>Defines how the content should be aligned vertically within the container. <strong>"top"</strong> indicates that content should be placed at the top. <strong>"center"</strong> and <strong>"bottom"</strong> function the same other than simply placing at center or at bottom.</td>
   </tr>
   </tbody>
   </table>

<h1>Details</h1>
 <p><strong>Option 1: No "stretch" value</strong></p>
 <ul> <li>The default value is "top"</li> </ul><p><strong>Option 2: "stretch" value</strong></p><ul> <li>The default value is "stretch"</li> </ul>
  <p>Most of the time, “top” and “stretch” are identical in behavior. <strong>It’s only when you also use height: stretch on one of the child elements that there would be a difference.</strong></p>
   <p><strong>If we go with Option 1, then it doesn’t matter what verticalContentAlignment the card author set, since the children content will collectively stretch to fill the height due to that child having a stretch height.</strong></p>
 <p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/13246069/40383724-67c29272-5db6-11e8-99af-581f609ac719.png"><img src="https://user-images.githubusercontent.com/13246069/40383724-67c29272-5db6-11e8-99af-581f609ac719.png" alt="image" style="max-width:100%;"></a></p> <ul>
   <li>Essentially, if a child has height: stretch, the verticalContentAlignment property on its parent becomes meaningless.</li> </ul>
   <p><strong>If we go with Option 2, then when verticalContentAlignment is set to anything except “stretch”, the children with stretch heights will essentially become auto heights, since the children content is no longer collectively stretching to fill the height.</strong></p>
   <p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/13246069/40383775-88451d80-5db6-11e8-9efa-0dbb07bdf7fc.png"><img src="https://user-images.githubusercontent.com/13246069/40383775-88451d80-5db6-11e8-9efa-0dbb07bdf7fc.png" alt="image" style="max-width:100%;"></a></p>
   <ul>
   <li>Essentially, if verticalContentAlignment is set to anything except stretch, its children height properties become meaningless.</li>
   </ul>

**Comment by BalajiR** [comment]
Implementation available in PR https://github.com/Imaginea/AdaptiveCards/pull/55/
