### ISSUE TITLE
[1.1] Extensibility - Styles

### ISSUE THREAD

**Issue by BalajiR** [Imaginea/AdaptiveCards#41]
To support `extensibility of element styles` in ReactNative renderer.
iOS and Android AC SDKs support style extensibility where the consumer app can override the styles applicable for elements. As of now, this is not documented by MS anywhere in adaptive-cards page(s). Have to explore the iOS/ Android source code for gathering the complete requirements w.r.t this.

Type | Supported
-- | --
HostConfig | Supported
Registry | Supported : Add / Remove entire element via Registry
Theme Config | **TODO** : To provide a way for host app to provide styles as a prop
Extending Component Render | **TODO** : To provide a way for consumer app to get access to the rendered element and add customization on the same.

**Comment by IbrahimSulai** [comment]
We have observed some extensibility in the native code,

1. The user can add custom container styles in the host config in addition to "default" and "emphasis" 
styles.

2. The user can override the style of the component by using the delegate method provided in the iOS native side.

**Comment by BalajiR** [comment]
Let us add the option for the Host app to provide custom styles via theme config (as a prop) to root element.

**Comment by BalajiR** [comment]
Extensibility via THEME CONFIG is implemented in PR  https://github.com/Imaginea/AdaptiveCards/pull/69
