### ISSUE TITLE
[1.1] ImageSet - Sizing issues on 'Auto' & 'Default'

### ISSUE THREAD

**Issue by BalajiR** [Imaginea/AdaptiveCards#47]
**Current** - Determined size is not as same as iOS SDK renders the Image.
**Expected** - Sizing determination should be same as iOS renderer.

**Comment by Surezt22** [comment]
As per iOS implementation, for an image set, when the size is undefined or auto, the size of the images are considered as medium.
 Followed the same implementation in iOS.

**Comment by Surezt22** [comment]
Fixed in the PR https://github.com/Imaginea/AdaptiveCards/pull/52
