### ISSUE TITLE
[1.1] Column - Default Spacing

### ISSUE THREAD

**Issue by BalajiR** [Imaginea/AdaptiveCards#48]
**About** : If the payload of an element doesn't has `spacing` value, `default` spacing must be taken. 
**Current** : In Column, "none" is being used as spacing when the details are not provided.
**Expected** : Use, the "default" spacing in the absence of its value in payload.

**Comment by Surezt22** [comment]
Fixed in the PR https://github.com/Imaginea/AdaptiveCards/issues/48
