### ISSUE TITLE
[1.1] Image - Support relative URLs

### ISSUE THREAD

**Issue by BalajiR** [Imaginea/AdaptiveCards#49]
**Current** : Only remote image URLs are supported but not local images.
**Expected** : Image element should also support relative URLs for the local assets.

**Comment by raghunandhan09** [comment]
With reference to the [Images handling](https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources) on react-native platform,
The local image handling has been implemented as below:
 - The local images should be added in the xcassets folder of xCode for iOS and in the drawable folder for Android (android/app/src/main/res/drawable).
 - The images should be named in the sample json in lower case alphabets (Android drawable folder doesn't support upper case).
 - The sample local image name format across the adaptive card jsons are configured as  ('Assets/Imagename.png'). The implementation has been done as per the same format.

The above are the assumptions and steps considered for the implementation of relative Image URLs. Please share your comments on the same.
